/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'josdem' at '4/12/16 3:35 PM' with Gradle 2.9
 *
 * @author josdem, @date 4/12/16 3:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
